task:
  type: object_nav
scene:
  nvidia_park:
    path: nvidia_edit/park/park_morning_edit.usd
    type: nvidia
    scale: 1.0
    collider: true
    episodes:
      number: 10
      goals:
        - "MailboxType.*"
        - "ParkBench.*"
        - "Hydrant_.*"