navmesh:
  default:
    agent_height: 0.3
    agent_max_climb: 0.05
    agent_max_slope: 26.0
    agent_radius: 0.3
    cell_height: 0.1
    cell_size: 0.08
    detail_sample_dist: 1.0
    detail_sample_max_error: 1.0
    edge_max_error: 1.3
    edge_max_len: 5.0
    region_merge_size: 0.5
    region_min_size: 0.5
    verts_per_poly: 6.0
  indoor:
    agent_height: 0.6
    agent_max_climb: 0.2
    agent_max_slope: 45.0
    agent_radius: 0.3
    cell_height: 0.05
    cell_size: 0.05
    detail_sample_dist: 1.0
    detail_sample_max_error: 0.0
    edge_max_error: 0.0
    edge_max_len: 0.0
    region_merge_size: 0.0
    region_min_size: 0.0
    verts_per_poly: 6.0
  vc:
    agent_height: 0.6000000238418579
    agent_max_climb: 0.2
    agent_max_slope: 45.0
    agent_radius: 0.5
    cell_height: 0.1
    cell_size: 1.5
    detail_sample_dist: 1.0
    detail_sample_max_error: 0.0
    edge_max_error: 0.0
    edge_max_len: 0.0
    region_merge_size: 0.0
    region_min_size: 0.0
    verts_per_poly: 6.0
scene:
  grCommercial:
    align_ground: false
    collider: true
    episodes:
      scene0:
        ceiling_height: 1.0
        episode_number: 20
        label: supermarket
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: indoor
        path: grscenes_commercial/scenes/scene0/start_result_navigation.usd
        rule_pattern: gr
      scene1:
        ceiling_height: 1.0
        episode_number: 20
        label: kindergarten
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: indoor
        path: grscenes_commercial/scenes/scene1/start_result_navigation.usd
        rule_pattern: gr
      scene11:
        ceiling_height: 1.0
        episode_number: 20
        label: hospital
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: indoor
        path: grscenes_commercial/scenes/scene11/start_result_navigation.usd
        rule_pattern: gr
      scene13:
        ceiling_height: 1.0
        episode_number: 20
        label: supermarket
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: indoor
        path: grscenes_commercial/scenes/scene13/start_result_navigation.usd
        rule_pattern: gr
      scene2:
        ceiling_height: 1.0
        episode_number: 20
        label: hospital
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: indoor
        path: grscenes_commercial/scenes/scene2/start_result_navigation.usd
        rule_pattern: gr
      scene26:
        ceiling_height: 1.0
        episode_number: 20
        label: cafe
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: indoor
        path: grscenes_commercial/scenes/scene26/start_result_navigation.usd
        rule_pattern: gr
      scene27:
        ceiling_height: 1.0
        episode_number: 20
        label: supermarket
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: indoor
        path: grscenes_commercial/scenes/scene27/start_result_navigation.usd
        rule_pattern: gr
      scene29:
        ceiling_height: 1.0
        episode_number: 20
        label: breakroom
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: indoor
        path: grscenes_commercial/scenes/scene29/start_result_navigation.usd
        rule_pattern: gr
      scene3:
        ceiling_height: 1.0
        episode_number: 20
        label: studyroom
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: indoor
        path: grscenes_commercial/scenes/scene3/start_result_navigation.usd
        rule_pattern: gr
      scene6:
        ceiling_height: 1.0
        episode_number: 20
        label: cafe
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: indoor
        path: grscenes_commercial/scenes/scene6/start_result_navigation.usd
        rule_pattern: gr
      scene7:
        ceiling_height: 1.0
        episode_number: 20
        label: supermarket
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: indoor
        path: grscenes_commercial/scenes/scene7/start_result_navigation.usd
        rule_pattern: gr
      scene8:
        ceiling_height: 1.0
        episode_number: 20
        label: kindergarden
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: indoor
        path: grscenes_commercial/scenes/scene8/start_result_navigation.usd
        rule_pattern: gr
      scene9:
        ceiling_height: 1.0
        episode_number: 20
        label: hospital
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: indoor
        path: grscenes_commercial/scenes/scene9/start_result_navigation.usd
        rule_pattern: gr
    scene_scale: 0.009999999776482582
  grHome:
    align_ground: false
    collider: true
    episodes:
      scene12:
        ceiling_height: 1.0
        episode_number: 20
        label: none
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: default
        path: grscenes_home/scenes/scene12/start_result_navigation.usd
        rule_pattern: gr
      scene13:
        ceiling_height: 1.0
        episode_number: 20
        label: none
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: default
        path: grscenes_home/scenes/scene13/start_result_navigation.usd
        rule_pattern: gr
      scene2:
        ceiling_height: 1.0
        episode_number: 20
        label: none
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: default
        path: grscenes_home/scenes/scene2/start_result_navigation.usd
        rule_pattern: gr
      scene21:
        ceiling_height: 1.0
        episode_number: 20
        label: none
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: default
        path: grscenes_home/scenes/scene21/start_result_navigation.usd
        rule_pattern: gr
      scene22:
        ceiling_height: 1.0
        episode_number: 20
        label: none
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: default
        path: grscenes_home/scenes/scene22/start_result_navigation.usd
        rule_pattern: gr
      scene33:
        ceiling_height: 1.0
        episode_number: 20
        label: none
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: default
        path: grscenes_home/scenes/scene33/start_result_navigation.usd
        rule_pattern: gr
      scene4:
        ceiling_height: 1.0
        episode_number: 20
        label: none
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: default
        path: grscenes_home/scenes/scene4/start_result_navigation.usd
        rule_pattern: gr
      scene40:
        ceiling_height: 1.0
        episode_number: 20
        label: none
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: default
        path: grscenes_home/scenes/scene40/start_result_navigation.usd
        rule_pattern: gr
      scene41:
        ceiling_height: 1.0
        episode_number: 20
        label: none
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: default
        path: grscenes_home/scenes/scene41/start_result_navigation.usd
        rule_pattern: gr
      scene48:
        ceiling_height: 1.0
        episode_number: 20
        label: none
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: default
        path: grscenes_home/scenes/scene48/start_result_navigation.usd
        rule_pattern: gr
      scene5:
        ceiling_height: 1.0
        episode_number: 20
        label: none
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: default
        path: grscenes_home/scenes/scene5/start_result_navigation.usd
        rule_pattern: gr
      scene58:
        ceiling_height: 1.0
        episode_number: 20
        label: none
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: default
        path: grscenes_home/scenes/scene58/start_result_navigation.usd
        rule_pattern: gr
      scene59:
        ceiling_height: 1.0
        episode_number: 20
        label: none
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: default
        path: grscenes_home/scenes/scene59/start_result_navigation.usd
        rule_pattern: gr
      scene66:
        ceiling_height: 1.0
        episode_number: 20
        label: none
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: default
        path: grscenes_home/scenes/scene66/start_result_navigation.usd
        rule_pattern: gr
      scene67:
        ceiling_height: 1.0
        episode_number: 20
        label: none
        navmesh_exclude:
        - /World/ground/terrain/__default_setting/HDR_Sphere/SM_Sphere
        navmesh_preset: default
        path: grscenes_home/scenes/scene67/start_result_navigation.usd
        rule_pattern: gr
    scene_scale: 0.009999999776482582
  nv:
    align_ground: true
    collider: true
    episodes:
      apartment:
        ceiling_height: 1.0
        episode_number: 20
        goal_rules:
          hydrant: Hydrant_.*
          light_switch: Lighting_Devices.*
          mailbox: MailboxType.*
          stair: Stairs_411731_0411731_35336
          stove: .*Stove.*
          trash_can: TrashCan.*
        navmesh_exclude:
        - /World/ground/terrain/sky_CloudySky/AxisNorth/SkySphere/Sphere
        navmesh_preset: default
        path: nvidia/park/apartment_flatten_edit.usd
        rule_pattern: name
      city1:
        ceiling_height: 1.0
        episode_number: 20
        goal_rules:
          hydrant: Hydrant_.*
          mailbox: MailboxType.*
          park_bench: ParkBench.*
          trash_bin: OutdoorTrash.*
          trash_can: TrashCan.*
        navmesh_exclude: []
        navmesh_preset: vc
        path: nvidia/city1/city1_flatten_edit.usd
        rule_pattern: name
      city2:
        ceiling_height: 1.0
        episode_number: 20
        goal_rules:
          hydrant: Hydrant_.*
          mailbox: MailboxType.*
          park_bench: ParkBench.*
          trash_bin: OutdoorTrash.*
          trash_can: TrashCan.*
        navmesh_exclude:
        - /World/ground/terrain/Ground/HorizonRT
        - /World/ground/terrain/Ground/HorizonRT_01
        navmesh_preset: vc
        path: nvidia/city2/city2_flatten_edit.usd
        rule_pattern: name
      parkmorning:
        ceiling_height: 1.0
        episode_number: 20
        goal_rules:
          hydrant: Hydrant_.*
          mailbox: MailboxType.*
          park_bench: ParkBench.*
          trash_bin: OutdoorTrash.*
          trash_can: TrashCan.*
        navmesh_exclude: []
        navmesh_preset: default
        path: nvidia/park/park_morning_flatten_edit.usd
        rule_pattern: name
      parknight:
        ceiling_height: 1.0
        episode_number: 20
        goal_rules:
          hydrant: Hydrant_.*
          mailbox: MailboxType.*
          park_bench: ParkBench.*
          trash_bin: OutdoorTrash.*
          trash_can: TrashCan.*
        navmesh_exclude:
        - /World/ground/terrain/sky_NightSky/AxisNorth/SkySphere/Sphere
        navmesh_preset: default
        path: nvidia/park/park_night_flatten_edit.usd
        rule_pattern: name
      parktest:
        ceiling_height: 1.0
        episode_number: 20
        goal_rules:
          hydrant: Hydrant_.*
          mailbox: MailboxType.*
          park_bench: ParkBench.*
        navmesh_exclude: []
        navmesh_preset: default
        path: nvidia/AECDemo_NVD@10012/Demos/AEC/BrownstoneDemo/test.usd
        rule_pattern: name
    scene_scale: 0.01
  test:
    align_ground: true
    collider: true
    episodes:
      generator:
        ceiling_height: 1.0
        episode_number: 20
        goal_rules:
          mesh: mesh
        navmesh_exclude: []
        navmesh_preset: default
        path: generator
        rule_pattern: name
    scene_scale: 1.0
  vc:
    align_ground: true
    collider: true
    episodes:
      amsterdam:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/AMSTERDAM/AMSTERDAM_store_merged.usd
        rule_pattern: vc
      amsterdam_store:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/AMSTERDAM/AMSTERDAM_store_merged.usd
        rule_pattern: vc_store
      austin:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/AUSTIN/AUSTIN_store_merged.usd
        rule_pattern: vc
      austin_store:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/AUSTIN/AUSTIN_store_merged.usd
        rule_pattern: vc_store
      baltimore:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/BALTIMORE/BALTIMORE_store_merged.usd
        rule_pattern: vc
      baltimore_store:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/BALTIMORE/BALTIMORE_store_merged.usd
        rule_pattern: vc_store
      barcelona:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/BARCELONA/BARCELONA_store_merged.usd
        rule_pattern: vc
      barcelona_store:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/BARCELONA/BARCELONA_store_merged.usd
        rule_pattern: vc_store
      belgrade:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/BELGRADE/BELGRADE_store_merged.usd
        rule_pattern: vc
      belgrade_store:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/BELGRADE/BELGRADE_store_merged.usd
        rule_pattern: vc_store
      berlin:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/BERLIN/BERLIN_store_merged.usd
        rule_pattern: vc
      berlin_store:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/BERLIN/BERLIN_store_merged.usd
        rule_pattern: vc_store
      boston:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/BOSTON/BOSTON_store_merged.usd
        rule_pattern: vc
      boston_store:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/BOSTON/BOSTON_store_merged.usd
        rule_pattern: vc_store
      london:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/LONDON/LONDON_store_merged.usd
        rule_pattern: vc
      london_store:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/LONDON/LONDON_store_merged.usd
        rule_pattern: vc_store
      madrid:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/MADRID/MADRID_store_merged.usd
        rule_pattern: vc
      madrid_store:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/MADRID/MADRID_store_merged.usd
        rule_pattern: vc_store
      ny:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/NY/NY_store_merged.usd
        rule_pattern: vc
      ny_store:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/NY/NY_store_merged.usd
        rule_pattern: vc_store
      paris:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/PARIS/PARIS_store_merged.usd
        rule_pattern: vc
      paris_store:
        ceiling_height: 1.0
        episode_number: 20
        navmesh_exclude: []
        navmesh_preset: vc
        path: vc_plus/PARIS/PARIS_store_merged.usd
        rule_pattern: vc_store
    scene_scale: 1.0
task:
  type: object_nav
