task:
  type: object_nav
scene:
  nv_park:
    path: nvidia_edit/park/park_morning_edit.usd
    type: nvidia
    scale: 1.0
    collider: true
    episodes:
      number: 30
      goals:
        mailbox: "MailboxType.*"
        park_bench: "ParkBench.*"
        hydrant: "Hydrant_.*"
  vc_berlin:
    path: virtual_community/BERLIN/BERLIN.usd
    type: virtual_community
    scale: 1.0
    collider: true
    align_ground: true
    episodes:
      number: 30
      goals:
        street_lamp: "Street_Lamp.*"
        city_bench: "City_Bench.*"
        tree: "Tree.*"